// §28 Phase 1 vitest unit — §22 prompt assertion. Pins the load-bearing
// "ONLY these folders" sentence in the system prompt fragment that
// claudeChat.ts appends when the request carries reference folders. Without
// this guard the agent regresses to roaming `~/Documents` (§22 background).
//
// The const lives in server/src/lib/referencePrompt.ts (extracted from the
// claudeChat.ts route in §28 Phase 1 specifically so this assertion can
// import it without dragging express/SDK/node deps into the vitest run).
// Agent mirror at agent/src/shared/lib/referencePrompt.ts is regenerated by
// scripts/sync-agent-shared.sh — so this single assertion covers both the
// dev Express server and the menu-bar agent.
//
// Drift caveats: the sync script catches *modification* drift via diff, but
// **deletion** of the source file would break vitest module resolution and
// fail this suite — same direction as the drift-check, just a louder failure.

import { describe, expect, it } from 'vitest';

import { REFERENCE_FOLDERS_PROMPT } from '../../server/src/lib/referencePrompt';

describe('REFERENCE_FOLDERS_PROMPT — §22 "ONLY these folders" guard', () => {
  it('contains the load-bearing "ONLY these folders" sentence', () => {
    const out = REFERENCE_FOLDERS_PROMPT(['/Users/me/resume']);
    expect(out).toContain('ONLY');
    expect(out).toContain('your ONLY source of user content');
  });

  it('lists every supplied path as a bullet', () => {
    const out = REFERENCE_FOLDERS_PROMPT(['/Users/me/resume', '/Users/me/notes']);
    expect(out).toContain('• /Users/me/resume');
    expect(out).toContain('• /Users/me/notes');
  });

  it('forbids `find ~` / `ls /Users/...` roaming (§22 hard guard)', () => {
    const out = REFERENCE_FOLDERS_PROMPT(['/x']);
    expect(out).toContain('find ~');
    expect(out).toContain('ls /Users/...');
  });

  it('directs deliverable writes to <cwd>/outputs/ (Complete Session merge contract)', () => {
    const out = REFERENCE_FOLDERS_PROMPT(['/x']);
    expect(out).toContain('<cwd>/outputs/');
    expect(out).toContain("Don't write into ref folders directly");
  });
});
