// §22 — system-prompt fragment appended when a chat carries reference folders.
// Extracted into its own zero-dep module so the frontend vitest suite can
// import + assert the string without pulling in express / SDK / node fs deps
// from claudeChat.ts. Single source of truth — claudeChat.ts imports from
// here and the agent mirror is regenerated by scripts/sync-agent-shared.sh
// (referencePrompt.ts is in the SHARED_LIB list).
//
// §19 background: without this fragment the agent answered "改一下我的简历"
// with a generic Gmail/Drive fallback even though the resume folder was
// mounted via additionalDirectories. §22 strengthened the prompt to forbid
// roaming `~/Documents` etc. — the "ONLY these folders" sentence is the
// load-bearing guard the vitest assertion pins.

export const REFERENCE_FOLDERS_PROMPT = (paths: string[]) =>
  `The user has attached reference folders to this project:\n${paths.map((p) => `  • ${p}`).join('\n')}\n\nThese folders are your ONLY source of user content. Do NOT use Bash \`find ~\`, \`ls /Users/...\`, or any Glob outside these paths. If the content isn't in these folders, say so explicitly. Don't roam other directories.\n\nWhen the user asks about content that may live in these folders (their resume, a design doc, meeting notes, etc.), Glob each folder to list candidates first, then Read the most likely match before answering. Don't fabricate external context (Gmail, Drive, calendar) when these folders are attached — if the answer isn't on disk, say so explicitly. You can Glob/Read/Grep these folders to understand context. Don't write into ref folders directly. Your deliverable file outputs go to \`<cwd>/outputs/<name>\` (matches the ARTIFACT_PROMPT convention) — the user can later choose to merge them into reference folders via the Complete Session UI. Files outside outputs/ won't be copied as ref folder merge targets.`;
